/**
 * THE LIVING LOGOS — Country Database
 * Directive 019: Searchable country index for locale-aware onboarding.
 * Each entry: code (ISO 3166-1 alpha-2), name, flag emoji, lat/lng center.
 */

export const COUNTRIES = [
    { code: "AF", name: "Afghanistan", flag: "🇦🇫", lat: 33.93, lng: 67.71 },
    { code: "AL", name: "Albania", flag: "🇦🇱", lat: 41.15, lng: 20.17 },
    { code: "DZ", name: "Algeria", flag: "🇩🇿", lat: 28.03, lng: 1.66 },
    { code: "AD", name: "Andorra", flag: "🇦🇩", lat: 42.55, lng: 1.60 },
    { code: "AO", name: "Angola", flag: "🇦🇴", lat: -11.20, lng: 17.87 },
    { code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬", lat: 17.06, lng: -61.80 },
    { code: "AR", name: "Argentina", flag: "🇦🇷", lat: -38.42, lng: -63.62 },
    { code: "AM", name: "Armenia", flag: "🇦🇲", lat: 40.07, lng: 45.04 },
    { code: "AU", name: "Australia", flag: "🇦🇺", lat: -25.27, lng: 133.78 },
    { code: "AT", name: "Austria", flag: "🇦🇹", lat: 47.52, lng: 14.55 },
    { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", lat: 40.14, lng: 47.58 },
    { code: "BS", name: "Bahamas", flag: "🇧🇸", lat: 25.03, lng: -77.40 },
    { code: "BH", name: "Bahrain", flag: "🇧🇭", lat: 26.07, lng: 50.56 },
    { code: "BD", name: "Bangladesh", flag: "🇧🇩", lat: 23.68, lng: 90.36 },
    { code: "BB", name: "Barbados", flag: "🇧🇧", lat: 13.19, lng: -59.54 },
    { code: "BY", name: "Belarus", flag: "🇧🇾", lat: 53.71, lng: 27.95 },
    { code: "BE", name: "Belgium", flag: "🇧🇪", lat: 50.50, lng: 4.47 },
    { code: "BZ", name: "Belize", flag: "🇧🇿", lat: 17.19, lng: -88.50 },
    { code: "BJ", name: "Benin", flag: "🇧🇯", lat: 9.31, lng: 2.32 },
    { code: "BT", name: "Bhutan", flag: "🇧🇹", lat: 27.51, lng: 90.43 },
    { code: "BO", name: "Bolivia", flag: "🇧🇴", lat: -16.29, lng: -63.59 },
    { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦", lat: 43.92, lng: 17.68 },
    { code: "BW", name: "Botswana", flag: "🇧🇼", lat: -22.33, lng: 24.68 },
    { code: "BR", name: "Brazil", flag: "🇧🇷", lat: -14.24, lng: -51.93 },
    { code: "BN", name: "Brunei", flag: "🇧🇳", lat: 4.54, lng: 114.73 },
    { code: "BG", name: "Bulgaria", flag: "🇧🇬", lat: 42.73, lng: 25.49 },
    { code: "BF", name: "Burkina Faso", flag: "🇧🇫", lat: 12.24, lng: -1.56 },
    { code: "BI", name: "Burundi", flag: "🇧🇮", lat: -3.37, lng: 29.92 },
    { code: "CV", name: "Cabo Verde", flag: "🇨🇻", lat: 16.00, lng: -24.01 },
    { code: "KH", name: "Cambodia", flag: "🇰🇭", lat: 12.57, lng: 104.99 },
    { code: "CM", name: "Cameroon", flag: "🇨🇲", lat: 7.37, lng: 12.35 },
    { code: "CA", name: "Canada", flag: "🇨🇦", lat: 56.13, lng: -106.35 },
    { code: "CF", name: "Central African Republic", flag: "🇨🇫", lat: 6.61, lng: 20.94 },
    { code: "TD", name: "Chad", flag: "🇹🇩", lat: 15.45, lng: 18.73 },
    { code: "CL", name: "Chile", flag: "🇨🇱", lat: -35.68, lng: -71.54 },
    { code: "CN", name: "China", flag: "🇨🇳", lat: 35.86, lng: 104.20 },
    { code: "CO", name: "Colombia", flag: "🇨🇴", lat: 4.57, lng: -74.30 },
    { code: "KM", name: "Comoros", flag: "🇰🇲", lat: -11.88, lng: 43.87 },
    { code: "CG", name: "Congo", flag: "🇨🇬", lat: -0.23, lng: 15.83 },
    { code: "CD", name: "Congo (DRC)", flag: "🇨🇩", lat: -4.04, lng: 21.76 },
    { code: "CR", name: "Costa Rica", flag: "🇨🇷", lat: 9.75, lng: -83.75 },
    { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮", lat: 7.54, lng: -5.55 },
    { code: "HR", name: "Croatia", flag: "🇭🇷", lat: 45.10, lng: 15.20 },
    { code: "CU", name: "Cuba", flag: "🇨🇺", lat: 21.52, lng: -77.78 },
    { code: "CY", name: "Cyprus", flag: "🇨🇾", lat: 35.13, lng: 33.43 },
    { code: "CZ", name: "Czech Republic", flag: "🇨🇿", lat: 49.82, lng: 15.47 },
    { code: "DK", name: "Denmark", flag: "🇩🇰", lat: 56.26, lng: 9.50 },
    { code: "DJ", name: "Djibouti", flag: "🇩🇯", lat: 11.83, lng: 42.59 },
    { code: "DM", name: "Dominica", flag: "🇩🇲", lat: 15.41, lng: -61.37 },
    { code: "DO", name: "Dominican Republic", flag: "🇩🇴", lat: 18.74, lng: -70.16 },
    { code: "EC", name: "Ecuador", flag: "🇪🇨", lat: -1.83, lng: -78.18 },
    { code: "EG", name: "Egypt", flag: "🇪🇬", lat: 26.82, lng: 30.80 },
    { code: "SV", name: "El Salvador", flag: "🇸🇻", lat: 13.79, lng: -88.90 },
    { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", lat: 1.65, lng: 10.27 },
    { code: "ER", name: "Eritrea", flag: "🇪🇷", lat: 15.18, lng: 39.78 },
    { code: "EE", name: "Estonia", flag: "🇪🇪", lat: 58.60, lng: 25.01 },
    { code: "SZ", name: "Eswatini", flag: "🇸🇿", lat: -26.52, lng: 31.47 },
    { code: "ET", name: "Ethiopia", flag: "🇪🇹", lat: 9.15, lng: 40.49 },
    { code: "FJ", name: "Fiji", flag: "🇫🇯", lat: -17.71, lng: 178.07 },
    { code: "FI", name: "Finland", flag: "🇫🇮", lat: 61.92, lng: 25.75 },
    { code: "FR", name: "France", flag: "🇫🇷", lat: 46.23, lng: 2.21 },
    { code: "GA", name: "Gabon", flag: "🇬🇦", lat: -0.80, lng: 11.61 },
    { code: "GM", name: "Gambia", flag: "🇬🇲", lat: 13.44, lng: -15.31 },
    { code: "GE", name: "Georgia", flag: "🇬🇪", lat: 42.32, lng: 43.36 },
    { code: "DE", name: "Germany", flag: "🇩🇪", lat: 51.17, lng: 10.45 },
    { code: "GH", name: "Ghana", flag: "🇬🇭", lat: 7.95, lng: -1.02 },
    { code: "GR", name: "Greece", flag: "🇬🇷", lat: 39.07, lng: 21.82 },
    { code: "GD", name: "Grenada", flag: "🇬🇩", lat: 12.12, lng: -61.68 },
    { code: "GT", name: "Guatemala", flag: "🇬🇹", lat: 15.78, lng: -90.23 },
    { code: "GN", name: "Guinea", flag: "🇬🇳", lat: 9.95, lng: -9.70 },
    { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼", lat: 11.80, lng: -15.18 },
    { code: "GY", name: "Guyana", flag: "🇬🇾", lat: 4.86, lng: -58.93 },
    { code: "HT", name: "Haiti", flag: "🇭🇹", lat: 18.97, lng: -72.29 },
    { code: "HN", name: "Honduras", flag: "🇭🇳", lat: 15.20, lng: -86.24 },
    { code: "HU", name: "Hungary", flag: "🇭🇺", lat: 47.16, lng: 19.50 },
    { code: "IS", name: "Iceland", flag: "🇮🇸", lat: 64.96, lng: -19.02 },
    { code: "IN", name: "India", flag: "🇮🇳", lat: 20.59, lng: 78.96 },
    { code: "ID", name: "Indonesia", flag: "🇮🇩", lat: -0.79, lng: 113.92 },
    { code: "IR", name: "Iran", flag: "🇮🇷", lat: 32.43, lng: 53.69 },
    { code: "IQ", name: "Iraq", flag: "🇮🇶", lat: 33.22, lng: 43.68 },
    { code: "IE", name: "Ireland", flag: "🇮🇪", lat: 53.14, lng: -7.69 },
    { code: "IL", name: "Israel", flag: "🇮🇱", lat: 31.05, lng: 34.85 },
    { code: "IT", name: "Italy", flag: "🇮🇹", lat: 41.87, lng: 12.57 },
    { code: "JM", name: "Jamaica", flag: "🇯🇲", lat: 18.11, lng: -77.30 },
    { code: "JP", name: "Japan", flag: "🇯🇵", lat: 36.20, lng: 138.25 },
    { code: "JO", name: "Jordan", flag: "🇯🇴", lat: 30.59, lng: 36.24 },
    { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", lat: 48.02, lng: 66.92 },
    { code: "KE", name: "Kenya", flag: "🇰🇪", lat: -0.02, lng: 37.91 },
    { code: "KI", name: "Kiribati", flag: "🇰🇮", lat: -3.37, lng: -168.73 },
    { code: "KW", name: "Kuwait", flag: "🇰🇼", lat: 29.31, lng: 47.48 },
    { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬", lat: 41.20, lng: 74.77 },
    { code: "LA", name: "Laos", flag: "🇱🇦", lat: 19.86, lng: 102.50 },
    { code: "LV", name: "Latvia", flag: "🇱🇻", lat: 56.88, lng: 24.60 },
    { code: "LB", name: "Lebanon", flag: "🇱🇧", lat: 33.85, lng: 35.86 },
    { code: "LS", name: "Lesotho", flag: "🇱🇸", lat: -29.61, lng: 28.23 },
    { code: "LR", name: "Liberia", flag: "🇱🇷", lat: 6.43, lng: -9.43 },
    { code: "LY", name: "Libya", flag: "🇱🇾", lat: 26.34, lng: 17.23 },
    { code: "LI", name: "Liechtenstein", flag: "🇱🇮", lat: 47.17, lng: 9.56 },
    { code: "LT", name: "Lithuania", flag: "🇱🇹", lat: 55.17, lng: 23.88 },
    { code: "LU", name: "Luxembourg", flag: "🇱🇺", lat: 49.82, lng: 6.13 },
    { code: "MG", name: "Madagascar", flag: "🇲🇬", lat: -18.77, lng: 46.87 },
    { code: "MW", name: "Malawi", flag: "🇲🇼", lat: -13.25, lng: 34.30 },
    { code: "MY", name: "Malaysia", flag: "🇲🇾", lat: 4.21, lng: 101.98 },
    { code: "MV", name: "Maldives", flag: "🇲🇻", lat: 3.20, lng: 73.22 },
    { code: "ML", name: "Mali", flag: "🇲🇱", lat: 17.57, lng: -4.00 },
    { code: "MT", name: "Malta", flag: "🇲🇹", lat: 35.94, lng: 14.38 },
    { code: "MH", name: "Marshall Islands", flag: "🇲🇭", lat: 7.13, lng: 171.18 },
    { code: "MR", name: "Mauritania", flag: "🇲🇷", lat: 21.01, lng: -10.94 },
    { code: "MU", name: "Mauritius", flag: "🇲🇺", lat: -20.35, lng: 57.55 },
    { code: "MX", name: "Mexico", flag: "🇲🇽", lat: 23.63, lng: -102.55 },
    { code: "FM", name: "Micronesia", flag: "🇫🇲", lat: 7.43, lng: 150.55 },
    { code: "MD", name: "Moldova", flag: "🇲🇩", lat: 47.41, lng: 28.37 },
    { code: "MC", name: "Monaco", flag: "🇲🇨", lat: 43.75, lng: 7.41 },
    { code: "MN", name: "Mongolia", flag: "🇲🇳", lat: 46.86, lng: 103.85 },
    { code: "ME", name: "Montenegro", flag: "🇲🇪", lat: 42.71, lng: 19.37 },
    { code: "MA", name: "Morocco", flag: "🇲🇦", lat: 31.79, lng: -7.09 },
    { code: "MZ", name: "Mozambique", flag: "🇲🇿", lat: -18.67, lng: 35.53 },
    { code: "MM", name: "Myanmar", flag: "🇲🇲", lat: 21.91, lng: 95.96 },
    { code: "NA", name: "Namibia", flag: "🇳🇦", lat: -22.96, lng: 18.49 },
    { code: "NR", name: "Nauru", flag: "🇳🇷", lat: -0.52, lng: 166.93 },
    { code: "NP", name: "Nepal", flag: "🇳🇵", lat: 28.39, lng: 84.12 },
    { code: "NL", name: "Netherlands", flag: "🇳🇱", lat: 52.13, lng: 5.29 },
    { code: "NZ", name: "New Zealand", flag: "🇳🇿", lat: -40.90, lng: 174.89 },
    { code: "NI", name: "Nicaragua", flag: "🇳🇮", lat: 12.87, lng: -85.21 },
    { code: "NE", name: "Niger", flag: "🇳🇪", lat: 17.61, lng: 8.08 },
    { code: "NG", name: "Nigeria", flag: "🇳🇬", lat: 9.08, lng: 8.68 },
    { code: "KP", name: "North Korea", flag: "🇰🇵", lat: 40.34, lng: 127.51 },
    { code: "MK", name: "North Macedonia", flag: "🇲🇰", lat: 41.51, lng: 21.75 },
    { code: "NO", name: "Norway", flag: "🇳🇴", lat: 60.47, lng: 8.47 },
    { code: "OM", name: "Oman", flag: "🇴🇲", lat: 21.47, lng: 55.98 },
    { code: "PK", name: "Pakistan", flag: "🇵🇰", lat: 30.38, lng: 69.35 },
    { code: "PW", name: "Palau", flag: "🇵🇼", lat: 7.51, lng: 134.58 },
    { code: "PS", name: "Palestine", flag: "🇵🇸", lat: 31.95, lng: 35.23 },
    { code: "PA", name: "Panama", flag: "🇵🇦", lat: 8.54, lng: -80.78 },
    { code: "PG", name: "Papua New Guinea", flag: "🇵🇬", lat: -6.31, lng: 143.96 },
    { code: "PY", name: "Paraguay", flag: "🇵🇾", lat: -23.44, lng: -58.44 },
    { code: "PE", name: "Peru", flag: "🇵🇪", lat: -9.19, lng: -75.02 },
    { code: "PH", name: "Philippines", flag: "🇵🇭", lat: 12.88, lng: 121.77 },
    { code: "PL", name: "Poland", flag: "🇵🇱", lat: 51.92, lng: 19.15 },
    { code: "PT", name: "Portugal", flag: "🇵🇹", lat: 39.40, lng: -8.22 },
    { code: "QA", name: "Qatar", flag: "🇶🇦", lat: 25.35, lng: 51.18 },
    { code: "RO", name: "Romania", flag: "🇷🇴", lat: 45.94, lng: 24.97 },
    { code: "RU", name: "Russia", flag: "🇷🇺", lat: 61.52, lng: 105.32 },
    { code: "RW", name: "Rwanda", flag: "🇷🇼", lat: -1.94, lng: 29.87 },
    { code: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳", lat: 17.36, lng: -62.78 },
    { code: "LC", name: "Saint Lucia", flag: "🇱🇨", lat: 13.91, lng: -60.98 },
    { code: "VC", name: "Saint Vincent", flag: "🇻🇨", lat: 12.98, lng: -61.29 },
    { code: "WS", name: "Samoa", flag: "🇼🇸", lat: -13.76, lng: -172.10 },
    { code: "SM", name: "San Marino", flag: "🇸🇲", lat: 43.94, lng: 12.46 },
    { code: "ST", name: "São Tomé and Príncipe", flag: "🇸🇹", lat: 0.19, lng: 6.61 },
    { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", lat: 23.89, lng: 45.08 },
    { code: "SN", name: "Senegal", flag: "🇸🇳", lat: 14.50, lng: -14.45 },
    { code: "RS", name: "Serbia", flag: "🇷🇸", lat: 44.02, lng: 21.01 },
    { code: "SC", name: "Seychelles", flag: "🇸🇨", lat: -4.68, lng: 55.49 },
    { code: "SL", name: "Sierra Leone", flag: "🇸🇱", lat: 8.46, lng: -11.78 },
    { code: "SG", name: "Singapore", flag: "🇸🇬", lat: 1.35, lng: 103.82 },
    { code: "SK", name: "Slovakia", flag: "🇸🇰", lat: 48.67, lng: 19.70 },
    { code: "SI", name: "Slovenia", flag: "🇸🇮", lat: 46.15, lng: 14.99 },
    { code: "SB", name: "Solomon Islands", flag: "🇸🇧", lat: -9.65, lng: 160.16 },
    { code: "SO", name: "Somalia", flag: "🇸🇴", lat: 5.15, lng: 46.20 },
    { code: "ZA", name: "South Africa", flag: "🇿🇦", lat: -30.56, lng: 22.94 },
    { code: "KR", name: "South Korea", flag: "🇰🇷", lat: 35.91, lng: 127.77 },
    { code: "SS", name: "South Sudan", flag: "🇸🇸", lat: 6.88, lng: 31.31 },
    { code: "ES", name: "Spain", flag: "🇪🇸", lat: 40.46, lng: -3.75 },
    { code: "LK", name: "Sri Lanka", flag: "🇱🇰", lat: 7.87, lng: 80.77 },
    { code: "SD", name: "Sudan", flag: "🇸🇩", lat: 12.86, lng: 30.22 },
    { code: "SR", name: "Suriname", flag: "🇸🇷", lat: 3.92, lng: -56.03 },
    { code: "SE", name: "Sweden", flag: "🇸🇪", lat: 60.13, lng: 18.64 },
    { code: "CH", name: "Switzerland", flag: "🇨🇭", lat: 46.82, lng: 8.23 },
    { code: "SY", name: "Syria", flag: "🇸🇾", lat: 34.80, lng: 39.00 },
    { code: "TW", name: "Taiwan", flag: "🇹🇼", lat: 23.70, lng: 120.96 },
    { code: "TJ", name: "Tajikistan", flag: "🇹🇯", lat: 38.86, lng: 71.28 },
    { code: "TZ", name: "Tanzania", flag: "🇹🇿", lat: -6.37, lng: 34.89 },
    { code: "TH", name: "Thailand", flag: "🇹🇭", lat: 15.87, lng: 100.99 },
    { code: "TL", name: "Timor-Leste", flag: "🇹🇱", lat: -8.87, lng: 125.73 },
    { code: "TG", name: "Togo", flag: "🇹🇬", lat: 8.62, lng: 0.82 },
    { code: "TO", name: "Tonga", flag: "🇹🇴", lat: -21.18, lng: -175.20 },
    { code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", lat: 10.69, lng: -61.22 },
    { code: "TN", name: "Tunisia", flag: "🇹🇳", lat: 33.89, lng: 9.54 },
    { code: "TR", name: "Turkey", flag: "🇹🇷", lat: 38.96, lng: 35.24 },
    { code: "TM", name: "Turkmenistan", flag: "🇹🇲", lat: 38.97, lng: 59.56 },
    { code: "TV", name: "Tuvalu", flag: "🇹🇻", lat: -7.11, lng: 177.65 },
    { code: "UG", name: "Uganda", flag: "🇺🇬", lat: 1.37, lng: 32.29 },
    { code: "UA", name: "Ukraine", flag: "🇺🇦", lat: 48.38, lng: 31.17 },
    { code: "AE", name: "United Arab Emirates", flag: "🇦🇪", lat: 23.42, lng: 53.85 },
    { code: "GB", name: "United Kingdom", flag: "🇬🇧", lat: 55.38, lng: -3.44 },
    { code: "US", name: "United States", flag: "🇺🇸", lat: 37.09, lng: -95.71 },
    { code: "UY", name: "Uruguay", flag: "🇺🇾", lat: -32.52, lng: -55.77 },
    { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", lat: 41.38, lng: 64.59 },
    { code: "VU", name: "Vanuatu", flag: "🇻🇺", lat: -15.38, lng: 166.96 },
    { code: "VA", name: "Vatican City", flag: "🇻🇦", lat: 41.90, lng: 12.45 },
    { code: "VE", name: "Venezuela", flag: "🇻🇪", lat: 6.42, lng: -66.59 },
    { code: "VN", name: "Vietnam", flag: "🇻🇳", lat: 14.06, lng: 108.28 },
    { code: "YE", name: "Yemen", flag: "🇾🇪", lat: 15.55, lng: 48.52 },
    { code: "ZM", name: "Zambia", flag: "🇿🇲", lat: -13.13, lng: 27.85 },
    { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", lat: -19.02, lng: 29.15 },
];

/**
 * 26 Supported Languages — native script display
 * Matches the Living Logos multilingual mandate.
 */
export const LANGUAGES = [
    { code: "ar", name: "العربية", english: "Arabic", dir: "rtl" },
    { code: "bg", name: "Български", english: "Bulgarian", dir: "ltr" },
    { code: "cs", name: "Čeština", english: "Czech", dir: "ltr" },
    { code: "de", name: "Deutsch", english: "German", dir: "ltr" },
    { code: "el", name: "Ελληνικά", english: "Greek", dir: "ltr" },
    { code: "en", name: "English", english: "English", dir: "ltr" },
    { code: "es", name: "Español", english: "Spanish", dir: "ltr" },
    { code: "et", name: "Eesti", english: "Estonian", dir: "ltr" },
    { code: "fi", name: "Suomi", english: "Finnish", dir: "ltr" },
    { code: "fr", name: "Français", english: "French", dir: "ltr" },
    { code: "he", name: "עברית", english: "Hebrew", dir: "rtl" },
    { code: "hi", name: "हिन्दी", english: "Hindi", dir: "ltr" },
    { code: "ja", name: "日本語", english: "Japanese", dir: "ltr" },
    { code: "ka", name: "ქართული", english: "Georgian", dir: "ltr" },
    { code: "ko", name: "한국어", english: "Korean", dir: "ltr" },
    { code: "mk", name: "Македонски", english: "Macedonian", dir: "ltr" },
    { code: "pl", name: "Polski", english: "Polish", dir: "ltr" },
    { code: "pt", name: "Português", english: "Portuguese", dir: "ltr" },
    { code: "ro", name: "Română", english: "Romanian", dir: "ltr" },
    { code: "ru", name: "Русский", english: "Russian", dir: "ltr" },
    { code: "sk", name: "Slovenčina", english: "Slovak", dir: "ltr" },
    { code: "sr", name: "Српски", english: "Serbian", dir: "ltr" },
    { code: "sw", name: "Kiswahili", english: "Swahili", dir: "ltr" },
    { code: "tr", name: "Türkçe", english: "Turkish", dir: "ltr" },
    { code: "uk", name: "Українська", english: "Ukrainian", dir: "ltr" },
    { code: "zh", name: "中文", english: "Chinese", dir: "ltr" },
];

/**
 * Find a country by ISO code.
 */
export function getCountryByCode(code) {
    return COUNTRIES.find((c) => c.code === code) || null;
}

/**
 * Search countries by name (case-insensitive partial match).
 */
export function searchCountries(query) {
    if (!query || !query.trim()) return COUNTRIES;
    const q = query.trim().toLowerCase();
    return COUNTRIES.filter((c) => c.name.toLowerCase().includes(q));
}
